ajout d'une option de choix de roles lors de la création d'un utilisa…
F-Jean/projet8-TodoList pull request #7
Opened 2022-10-24 12:20 UTC by F-Jean

…teur.

Ajout de isGranted ROLE_ADMIN à UserController;
Ajout d'un utilisateur admin (Jean);
Création d'un message d'erreur 403 pour les non admins s'ils essaient de forcer l'accès à la route depuis l'URL;
Modification des autorisations dans les vues twig;
Modification du Form UserType pour ajouter le choix des roles (ROLE_ADMIN & ROLE_USER).

2022-10-24 14:53 UTC, F-Jean commented
Pour simplifier le choix des rôles :
un user est soit un admin soit un user, pas besoin d'un array, un user ne peut pas avoir plusieurs rôles => remplacement de $roles de type array par $role de type string dans User entity + ajout getters/setter;
donc suppression du data transformer dans le UserType form;
ajout de role_hierarchy dans security.yaml pour éviter le access denied.

2022-10-26 08:37 UTC, TBoileau requested changes

2022-10-26 08:37 UTC, TBoileau commented on src/Security/TaskVoter.php
> +        if ($user === $task->getUser() or $this->security->isGranted('ROLE_ADMIN')) {
ne pas utiliser le `or` mais plutôt le `||`, ça ne fonctionne pas de la même manière

2022-10-26 13:01 UTC, F-Jean commented
modification du TaskVoter afin qu'il gère qu'une tâche ne soit gérer que par son auteur ou un admin, et que les tâches anonymes ne soient gérer que par les admin pour l'EDIT, le DELETE et le TOGGLE.

2022-10-27 13:57 UTC, F-Jean commented
modification des fixtures : 
    - TaskFixtures : ajout de tâches liées à des users pour qu'elles ne soient pas anonyme pour les tests;
    - UserFixtures : ajout de users utilisés pour l'ajout des 3 nouvelles tâches;

modification de TaskType & UserType : ajout de l'option 'empty_data' sur certains champs pour pouvoir testé les cas de blank lors de l'édition;

modification des tests :
    - Security/RegistrationTest;
    - Task/DeleteTest;
    - Task/ShowTest;
    - Task/ToggleTest;
    - Task/UpdateTest;
    - User/ShowTest;
    - User/UpdateTest.

2022-10-28 10:50 UTC, TBoileau requested changes

2022-10-28 10:50 UTC, TBoileau commented on src/Security/TaskVoter.php
> +        if ($user === $task->getUser() || $this->security->isGranted('ROLE_ADMIN')) {
tu peux directement faire : 
```php
return $user === $task->getUser() || $this->security->isGranted('ROLE_ADMIN');
```

2022-10-28 10:50 UTC, TBoileau commented on templates/base.html.twig
> +            {% if app.user and is_granted('ROLE_ADMIN') %}
tu peux supprimer le `app.user`

2022-10-28 10:50 UTC, TBoileau commented on templates/base.html.twig
>                  {% if app.user %}
je te conseille plutôt de faire un `is_granted('ROLE_USER')`

2022-10-28 12:06 UTC, F-Jean commented on src/Security/TaskVoter.php
> +        if ($user === $task->getUser() || $this->security->isGranted('ROLE_ADMIN')) {
fait

2022-10-28 12:06 UTC, F-Jean commented
requested changes effectués

2022-10-28 12:06 UTC, merged